---
- name: Test
  hosts: webservers
  remote_user: ubuntu
  become: true

  tasks:
    - name: Move file from controller to target nodes.
      copy:
        src: /home/ubuntu/WordPressDevops/ansible/testAutomation.txt
        dest: /home/ubuntu/testAutomation.txt
        