name: Deploy Ansible

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Change to ansible directory and run playbook
      run: cd ansible && ansible-playbook test.yml